/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import BeanClasses.DepartmentBean;
import BeanClasses.Exam_FormBean;
import BeanClasses.SemesterBean;
import java.awt.Dimension;
import java.awt.Toolkit;
import DB_Management.*;
import com.itextpdf.text.BaseColor;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Random
 */
public class Clerk_Form extends javax.swing.JFrame {

    /**
     * Creates new form Clerk_Form
     */
    public Clerk_Form() throws Exception {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("muet_logo.png")));

        Toolkit kit = this.getToolkit();
        Dimension size = kit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);



        buttonGroup1.add(Ann);
        buttonGroup1.add(suplemtnr);

    }

    public void getsub(int sm_id, int d_id) throws Exception {
        //   DepartmentBean bean = (DepartmentBean) dpt_ComboBox1.getSelectedItem();
        // SemesterBean sb = (SemesterBean) smstr_ComboBox2.getSelectedItem();
        Vector v = DBM_system.get_Sub(sm_id, d_id);
        for (int i = 0; i < v.size(); i++) {
            if (i == 0) {
                sub1_name_txt8.setText(v.elementAt(i) + "");
            }
            if (i == 1) {
                sub2_name_txt9.setText(v.elementAt(i) + "");
            }
            if (i == 2) {
                sub3_name_txt10.setText(v.elementAt(i) + "");
            }
            if (i == 3) {
                sub4name_txt11.setText(v.elementAt(i) + "");
            }
            if (i == 4) {
                sub5_name_txt12.setText(v.elementAt(i) + "");
            }

            if (i == 5) {
                sub6_name_txt13.setText(v.elementAt(i) + "");
            }
            if (i == 6) {
                sub7_txt14.setText(v.elementAt(i) + "");
            }
            if (i == 7) {
                sub8_name_txt15.setText(v.elementAt(i) + "");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        studentDetail_Panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        f_name_txt1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rollno_name_txt4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Ann = new javax.swing.JRadioButton();
        suplemtnr = new javax.swing.JRadioButton();
        sub1_name_txt8 = new javax.swing.JTextField();
        sub2_name_txt9 = new javax.swing.JTextField();
        sub3_name_txt10 = new javax.swing.JTextField();
        sub4name_txt11 = new javax.swing.JTextField();
        sub5_name_txt12 = new javax.swing.JTextField();
        sub6_name_txt13 = new javax.swing.JTextField();
        sub7_txt14 = new javax.swing.JTextField();
        sub8_name_txt15 = new javax.swing.JTextField();
        sub_9name_txt16 = new javax.swing.JTextField();
        sub10_name_txt17 = new javax.swing.JTextField();
        sub_11name_txt18 = new javax.swing.JTextField();
        sub12_name_txt19 = new javax.swing.JTextField();
        date_name_txt5 = new javax.swing.JTextField();
        contact_name_txt6 = new javax.swing.JTextField();
        fee_name_txt7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        feeSubmit_name_txt6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        chalan_txt15 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        dptname_txt1 = new javax.swing.JTextField();
        smstrname_txt2 = new javax.swing.JTextField();
        print_Button1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        clerk_srch_txt = new javax.swing.JTextField();
        search_jButton2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentDetail_Panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Submitted", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel1.setText("Name");

        jLabel2.setText("Father Name");

        rollno_name_txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollno_name_txt4ActionPerformed(evt);
            }
        });

        jLabel6.setText("Roll  no");

        jLabel5.setText("Fee");

        jLabel7.setText("Contact");

        jLabel8.setText("Date");

        jLabel9.setText("Exam Type");

        Ann.setText("Annual");

        suplemtnr.setText("Supplementary");
        suplemtnr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suplemtnrActionPerformed(evt);
            }
        });

        sub1_name_txt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub1_name_txt8ActionPerformed(evt);
            }
        });

        sub7_txt14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub7_txt14ActionPerformed(evt);
            }
        });

        sub8_name_txt15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub8_name_txt15ActionPerformed(evt);
            }
        });

        sub10_name_txt17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub10_name_txt17ActionPerformed(evt);
            }
        });

        sub_11name_txt18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_11name_txt18ActionPerformed(evt);
            }
        });

        fee_name_txt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fee_name_txt7ActionPerformed(evt);
            }
        });

        jLabel12.setText("Semester");

        jLabel13.setText("Department");

        jLabel14.setText("Fee Paid");

        jLabel15.setText("Challan no");

        chalan_txt15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chalan_txt15ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Subjects");

        javax.swing.GroupLayout studentDetail_Panel1Layout = new javax.swing.GroupLayout(studentDetail_Panel1);
        studentDetail_Panel1.setLayout(studentDetail_Panel1Layout);
        studentDetail_Panel1Layout.setHorizontalGroup(
            studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentDetail_Panel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentDetail_Panel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(studentDetail_Panel1Layout.createSequentialGroup()
                        .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(studentDetail_Panel1Layout.createSequentialGroup()
                                .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                                .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(contact_name_txt6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(fee_name_txt7)
                                    .addComponent(date_name_txt5)
                                    .addComponent(feeSubmit_name_txt6)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentDetail_Panel1Layout.createSequentialGroup()
                                .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(f_name_txt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(name_txt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rollno_name_txt4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dptname_txt1)
                                    .addComponent(smstrname_txt2))))
                        .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(studentDetail_Panel1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ann)
                                    .addComponent(chalan_txt15, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(182, 182, 182))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentDetail_Panel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentDetail_Panel1Layout.createSequentialGroup()
                                        .addComponent(suplemtnr)
                                        .addGap(160, 160, 160))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentDetail_Panel1Layout.createSequentialGroup()
                                        .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(studentDetail_Panel1Layout.createSequentialGroup()
                                                .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(sub5_name_txt12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(sub6_name_txt13, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(sub4name_txt11, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(sub3_name_txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(sub2_name_txt9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(sub1_name_txt8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(47, 47, 47)
                                                .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(sub12_name_txt19, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(sub10_name_txt17, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(sub7_txt14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(sub_9name_txt16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(sub_11name_txt18, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(sub8_name_txt15, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(38, 38, 38))))))))
        );
        studentDetail_Panel1Layout.setVerticalGroup(
            studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentDetail_Panel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ann)
                    .addComponent(suplemtnr)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dptname_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chalan_txt15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smstrname_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(f_name_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sub1_name_txt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sub7_txt14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rollno_name_txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sub2_name_txt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sub8_name_txt15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(studentDetail_Panel1Layout.createSequentialGroup()
                        .addComponent(fee_name_txt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sub5_name_txt12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(date_name_txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(studentDetail_Panel1Layout.createSequentialGroup()
                        .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sub3_name_txt10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sub_9name_txt16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contact_name_txt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub4name_txt11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub10_name_txt17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(sub_11name_txt18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentDetail_Panel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(sub12_name_txt19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(studentDetail_Panel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(studentDetail_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(feeSubmit_name_txt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub6_name_txt13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        print_Button1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        print_Button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print-icon.png"))); // NOI18N
        print_Button1.setText("Print");
        print_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_Button1ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_label.png"))); // NOI18N

        clerk_srch_txt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Roll Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14), new java.awt.Color(255, 0, 51))); // NOI18N

        search_jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        search_jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-search-icon.png"))); // NOI18N
        search_jButton2.setText("Search");
        search_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_jButton2ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(clerk_srch_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(search_jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(print_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton2))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(studentDetail_Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clerk_srch_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(search_jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(print_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(studentDetail_Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollno_name_txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollno_name_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollno_name_txt4ActionPerformed

    private void sub1_name_txt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub1_name_txt8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub1_name_txt8ActionPerformed

    private void sub7_txt14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub7_txt14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub7_txt14ActionPerformed

    private void suplemtnrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suplemtnrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suplemtnrActionPerformed

    private void fee_name_txt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fee_name_txt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fee_name_txt7ActionPerformed

    private void sub_11name_txt18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_11name_txt18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub_11name_txt18ActionPerformed

    private void sub10_name_txt17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub10_name_txt17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub10_name_txt17ActionPerformed

    private void search_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_jButton2ActionPerformed
        try {
            String rollno = clerk_srch_txt.getText();
            Exam_FormBean efb = DBM_system.get_submit_Samjh(rollno);
            if (efb == null) {
                return;
            }

            name_txt.setText(efb.getEx_name());
            f_name_txt1.setText(efb.getF_name());
            rollno_name_txt4.setText(efb.getRollno());
            fee_name_txt7.setText(efb.getEx_fee());
            contact_name_txt6.setText(efb.getContct());
            date_name_txt5.setText(efb.getAdm_date() + "");
            feeSubmit_name_txt6.setText(efb.getPrint_challan() + "");
            String ex_type = efb.getEx_typ();
            if (ex_type.equalsIgnoreCase("Annual")) {
                Ann.setSelected(true);
            }
            if (ex_type.equalsIgnoreCase("Supplementary")) {
                suplemtnr.setSelected(true);
            }

            chalan_txt15.setText(efb.getChallano() + "");
            int smstr = efb.getSmstr_id();
            int dept_id = efb.getDpt_id();

            getsub(smstr, dept_id);

            DepartmentBean bean = DBM_system.getClarkdpt(dept_id);
            dptname_txt1.setText(bean + "");
            SemesterBean clerksmstr = DBM_system.getClerksmstr(smstr);
            smstrname_txt2.setText(clerksmstr + "");

        } catch (Exception e) {
        }
    }//GEN-LAST:event_search_jButton2ActionPerformed

    private void chalan_txt15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chalan_txt15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chalan_txt15ActionPerformed

    private void sub8_name_txt15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub8_name_txt15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub8_name_txt15ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            new LoginForm().setVisible(true);
            this.hide();
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(Clerk_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void print_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_Button1ActionPerformed
        if (!clerk_srch_txt.equals(null)) {
            try {
                String name = name_txt.getText();
                String fname = f_name_txt1.getText();
                String rollno = rollno_name_txt4.getText();
                String dpt = dptname_txt1.getText();
                String smstr = smstrname_txt2.getText();
                String fee = fee_name_txt7.getText();
                String contct = contact_name_txt6.getText();
                String date = date_name_txt5.getText();
                String Fee_submitted = feeSubmit_name_txt6.getText();
                String exm_type = null;
                if (Ann.isSelected()) {
                    exm_type = Ann.getText();
                }
                if (suplemtnr.isSelected()) {
                    exm_type = suplemtnr.getText();
                }

                int chalanno = Integer.parseInt(chalan_txt15.getText() + "");

                JFileChooser jfc = new JFileChooser();
                jfc.setSelectedFile(new File(name_txt.getText() + " Exam form .pdf"));

                int dialog_result = jfc.showSaveDialog(null);
                if (dialog_result == jfc.APPROVE_OPTION) {

                    String FilePath = jfc.getSelectedFile().getPath();
                    Document document = new Document();
                    PdfWriter pdfWriter = PdfWriter.getInstance(document, new FileOutputStream(FilePath));

                    document.open();
                    document.add(new Paragraph("        Mehran University of Engineering and Technology", FontFactory.getFont(FontFactory.TIMES_BOLD, 15, Font.BOLD)));
                    document.add(new Paragraph("                        Examination Form                 ", FontFactory.getFont(FontFactory.TIMES_BOLD, 15, Font.BOLD)));
                    document.add(new Paragraph(new Date().toString()));
                    document.add(new Paragraph("-------------------------------------------------------------------------", FontFactory.getFont(FontFactory.TIMES_BOLD, 15, Font.BOLD)));
                    document.add(new Paragraph("Student Details", FontFactory.getFont(FontFactory.TIMES_BOLD, 15, Font.BOLD)));
                    document.add(new Paragraph("Name :      " + name, FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph("Father Name :      " + fname, FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph("Roll Number :      " + rollno, FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph("Departmetn :      " + dpt, FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph("Semester :      " + smstr, FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph("Fee :      " + fee, FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph("Contact :      " + contct, FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph("Date :      " + date, FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph("Exam Fee :      " + Fee_submitted, FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph("Exam  Type :      " + exm_type, FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph("Challan no :      " + chalanno, FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph("-------------------------------------------------------------------------", FontFactory.getFont(FontFactory.TIMES_BOLD, 15, Font.BOLD)));
                    document.add(new Paragraph("Subjects ", FontFactory.getFont(FontFactory.TIMES_BOLD, 15, Font.BOLD)));
                    document.add(new Paragraph(sub1_name_txt8.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph(sub2_name_txt9.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph(sub3_name_txt10.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph(sub4name_txt11.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph(sub5_name_txt12.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.getStyleValue("Verdana"))));
                    document.add(new Paragraph(sub6_name_txt13.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph(sub7_txt14.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph(sub8_name_txt15.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph(sub_9name_txt16.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph(sub10_name_txt17.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));

                    /* starting challan .*/
                    Exam_FormBean efb = DBM_system.get_submit_Samjh(rollno);
                    if (efb == null) {
                        return;
                    }
                    
                    
                    document.add(new Paragraph("____________________________________________________________", FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph("------------------------------------------------------------", FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph(" Challan             ", FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph(" HBL MUET University              ", FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph(" Sub-Branch Jamshoro              ", FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph("                                  Office copy   ", FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph(" A/C No:                          " + efb.getAcc(), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph(" Challan no:                      " + efb.getChallano(), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph(" Reg: no :   _____________________", FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                    document.add(new Paragraph(" Full Name :                      " + name, FontFactory.getFont(FontFactory.TIMES_BOLD, 8, Font.BOLD)));
                    document.add(new Paragraph(" Exam Fee :                       " + fee, FontFactory.getFont(FontFactory.TIMES_BOLD, 8, Font.BOLD)));
                    document.add(new Paragraph(" Fee Paid :                       " + Fee_submitted, FontFactory.getFont(FontFactory.TIMES_BOLD, 8, Font.BOLD)));
                    document.add(new Paragraph(" -----------------------------------------------", FontFactory.getFont(FontFactory.TIMES_BOLD, 8, Font.BOLD)));
                    document.add(new Paragraph(" Amount in words: One Thousand Six hundred only            ", FontFactory.getFont(FontFactory.TIMES_BOLD, 8, Font.BOLD)));
                    document.add(new Paragraph("-------------------------------------------------", FontFactory.getFont(FontFactory.TIMES_BOLD, 8, Font.BOLD)));
                    document.add(new Paragraph(" Manager :                     Cashier:                                 ", FontFactory.getFont(FontFactory.TIMES_BOLD, 8, Font.BOLD)));
                    document.add(new Paragraph(" ______________                ___________________ ", FontFactory.getFont(FontFactory.TIMES_BOLD, 8, Font.BOLD)));


                    document.close();


                    JOptionPane.showMessageDialog(null, "Exam form downloaded...");

                }

            } catch (DocumentException | FileNotFoundException ex) {
                Logger.getLogger(Clerk_Form.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No record found..");
        }

    }//GEN-LAST:event_print_Button1ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clerk_Form.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clerk_Form.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clerk_Form.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clerk_Form.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Clerk_Form().setVisible(true);


                } catch (Exception ex) {
                    Logger.getLogger(Clerk_Form.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Ann;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField chalan_txt15;
    private javax.swing.JTextField clerk_srch_txt;
    private javax.swing.JTextField contact_name_txt6;
    private javax.swing.JTextField date_name_txt5;
    private javax.swing.JTextField dptname_txt1;
    private javax.swing.JTextField f_name_txt1;
    private javax.swing.JTextField feeSubmit_name_txt6;
    private javax.swing.JTextField fee_name_txt7;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name_txt;
    private javax.swing.JButton print_Button1;
    private javax.swing.JTextField rollno_name_txt4;
    private javax.swing.JButton search_jButton2;
    private javax.swing.JTextField smstrname_txt2;
    private javax.swing.JPanel studentDetail_Panel1;
    private javax.swing.JTextField sub10_name_txt17;
    private javax.swing.JTextField sub12_name_txt19;
    private javax.swing.JTextField sub1_name_txt8;
    private javax.swing.JTextField sub2_name_txt9;
    private javax.swing.JTextField sub3_name_txt10;
    private javax.swing.JTextField sub4name_txt11;
    private javax.swing.JTextField sub5_name_txt12;
    private javax.swing.JTextField sub6_name_txt13;
    private javax.swing.JTextField sub7_txt14;
    private javax.swing.JTextField sub8_name_txt15;
    private javax.swing.JTextField sub_11name_txt18;
    private javax.swing.JTextField sub_9name_txt16;
    private javax.swing.JRadioButton suplemtnr;
    // End of variables declaration//GEN-END:variables
}
